public __sistema,pcodusu,W_USUA,pperfil,DIR_TEMPORAL,DIR_TRANSFER,DIR_DN,DIRTEMPORAL,DIR_BASES,MSGSEGURIDAD 
SET PROCEDURE TO LIBRERIA
set multilocks on
__sistema = "ACARA"
pcodusu = ""
pperfil ="ADM"
W_USUA="RFASANO"
ppgm = "APO0111"
DIR_LISTADO = "\WACAFAC\"
FSISTEMA = DATE()
DIR_TEMPORAL = "C:\TEMP\"
DIRTEMPORAL = DIR_TEMPORAL
DIR_TRANSFER = "\WACAFAC\TRA\"
DIR_DN = "\WACAFAC\DN\"
MSGSEGURIDAD = .f.
