SET OPTIMIZE ON
SET TALK OFF
SET ESCAPE OFF
SET CENTURY ON
SET DATE TO FRENCH
SET DELETED ON
SET CONFIRM ON
SET EXCLUSIVE OFF
SET DEFAULT TO SYS(2003)
SET POINT TO "."
SET SEPARATOR TO ","
SET SAFETY OFF
SET BELL OFF
SET ANSI ON

*********************
SET LOCK ON
SET REPROCESS TO AUTOMATIC
SET MULTILOCKS ON
*********************
SET PROCEDURE TO LIBRERIA


PUBLIC DIRTEMPORAL, DIR_TEMPORAL

DIRTEMPORAL  = "C:\temp\"
DIR_TEMPORAL = DIRTEMPORAL

*
IF !OK_TEMP()
   CLOSE TABLE ALL
   QUIT             	
ENDIF	

*********************
SET DEFAULT TO SYS(2003)
SET PATH TO BASES, PRG, FORM, MENU, CLASES, INF, BMP
*********************
SET SYSMENU TO 
_SCREEN.CLOSABLE=.F.
_SCREEN.ICON="icono.ico"
_SCREEN.CAPTION="Seguimiento de Sistemas" 
_SCREEN.WINDOWSTATE=2

OK = .F.

DO FORM SEG WITH OK

IF !OK
   CLOSE TABLE ALL
   QUIT
ENDIF

SET MESSAGE TO " V 1.00.0001 © 2000 " 

OPEN DATABASE wss SHARED && Abre la base de datos 
SET DATABASE TO wss

ON ERROR DO errhand WITH ;
	ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )

SET NOTIFY OFF
*
ON SHUTDOWN  DO SALIDA
*
*  
 DO MENU1.MPR


